### ISSUE TITLE
A2 - Clarifications

### ISSUE THREAD

**Issue by Leoariel** [CISC-CMPE-327/Information#55]
Hello,

My group is struggling to understand where to start with assignment 2. 

What type of diagram is wanted, would it be similar to the ones in lecture p2-1 page 14?
Are we meant to modify the classes? Can we move functions around? What exactly are the classes?
In assignment 1 after a while there was a sample row posted, could we get something similar for this assignment to help us get started?

**Comment by steven-hh-ding** [comment]
which option are you guys taking?

**Comment by Leoariel** [comment]
The web option

**Comment by steven-hh-ding** [comment]
Basically assuming that we know nothing about your program (or the template), how can you tell us the overall design and classes/functions (e.g. route functions & model class user)? You can use draw.io. There is no standard format/table (e.g. UML Diagram) since it is beyond the scope of this course. As long as it clearly shows your design and describe component/elements should be fine !


You can do whatever you need to the template to meet the specifications. The provided template is just a template (and it may not meet some of the specifications).
